name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  date_picker_timeline: ^1.2.5
  material_design_icons_flutter: ^5.0.6996
  font_awesome_flutter: 10.5.0
  shared_preferences: ^2.2.1
  device_info_plus: ^9.0.3
  connectivity_plus: ^4.0.2
  image_picker: ^1.0.4
  responsive_sizer: ^3.2.0
  permission_handler: ^11.0.1
  email_validator: ^2.1.17
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.4
  dio: 5.3.3
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1
  jiffy: ^6.2.1
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  mobile_number: ^2.1.1
  pinput: ^3.0.1
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.5
  cached_network_image: ^3.3.0
  fdottedline_nullsafety: ^2.0.1
  geolocator: ^10.1.0
  shimmer: ^3.0.0
  scratcher: ^2.4.0
  razorpay_flutter: ^1.3.5
  geocoding: ^2.1.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.0.0+1
  mapbox_search: ^3.2.0
  google_maps_flutter: ^2.5.0
  flutter_mapbox_autocomplete: ^2.0.0
  flutter_paystack: ^1.0.7
  flutter_html: ^3.0.0-beta.2
  share_plus: 7.1.0
  url_launcher: ^6.1.14
  flutter_easyloading: ^3.0.5
  provider: 6.0.5
  photo_view: ^0.14.0
  sign_in_with_apple: ^5.0.0
  flutter_google_places: ^0.3.0

dependency_overrides:
  flutter_svg: ^1.0.3
  intl: ^0.18.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "ic_launcher"
  ios: false
  remove_alpha_ios: true
  image_path: "assets/logo.png"
#  image_path: "assets/roundicon.png"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 500
        - asset: assets/fonts/poppins_medium.ttf
          weight: 400
        
    
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
