// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPKZ_bZQjPeS0uN-jQutPv00-GvWUMdTI',
    appId: '1:632725223997:web:34793cacac3510d3d4c854',
    messagingSenderId: '632725223997',
    projectId: 'weirdo-353b6',
    authDomain: 'weirdo-353b6.firebaseapp.com',
    storageBucket: 'weirdo-353b6.appspot.com',
    measurementId: 'G-K9LBNVN5QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3PkN5qkqO-y-niYJYl9Hb41Rgxh0xP0',
    appId: '1:632725223997:android:a182efc4b0b26596d4c854',
    messagingSenderId: '632725223997',
    projectId: 'weirdo-353b6',
    storageBucket: 'weirdo-353b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO9d6FwW--PcwkXdXtxI5_6D-8iWns1qQ',
    appId: '1:632725223997:ios:54744131af57e171d4c854',
    messagingSenderId: '632725223997',
    projectId: 'weirdo-353b6',
    storageBucket: 'weirdo-353b6.appspot.com',
    iosBundleId: 'com.app.weirdo',
  );
}
